name: ci
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CI_XCODE: '/Applications/Xcode_14.2.app/Contents/Developer'

concurrency:
   group: ${{ github.workflow }}-${{ github.ref }}
   cancel-in-progress: true

jobs:
  ios:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build-Test
      run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -project SnapCat.xcodeproj -scheme SnapCat -destination platform\=iOS\ Simulator,name\=iPhone\ 12\ Pro\ Max build | xcpretty
      env:
          DEVELOPER_DIR: ${{ env.CI_XCODE }}
